version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: flask_postgres
    environment:
      POSTGRES_USER: rwc
      POSTGRES_PASSWORD: changemeinprod
      POSTGRES_DB: biotrain
    ports:
      - "5436:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
